version: '3'

services:
  chatwebapp:
    build: .
    container_name: chat-web-app
    ports:
      - 3000:3000
    networks:
      - fclx
    volumes:
      - .:/home/node/app
    depends_on:
      - chatwebdb

  chatwebdb:
    image: mysql:8.0.30-debian
    container_name: chat-web-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    networks:
      - fclx
    volumes:
      - .docker/db:/var/lib/mysql
  
networks:
  fclx:
    external: true